# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Api tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: start mongo
        run: |
          docker compose -f mongo.yml up -d
      - name: Wait for MongoDB
        run: |
          # Sprawdza co 1 sekundę czy port 27017 na localhost jest otwarty
          timeout 60s bash -c 'until nc -z localhost 27017; do echo "Czekam na Mongo..."; sleep 1; done'
          echo "Mongo wystartowało!"
      - name: Start flask
        run: |
          export FLASK_APP=app/api.py
          export FLASK_ENV=development
          export PYTHONPATH=$GITHUB_WORKSPACE
          flask run &

      - name: Execute API tests
        run: |
          python3 -m pytest tests/api
